# Repository의 Actions 탭에 나타날 Workflow 이름으로 필수 옵션은 아닙니다.
name: deploy

# Workflow를 실행시키기 위한 Event 목록입니다.
on:
  # 하단 코드에 따라 develop 브랜치에 Push 또는 Pull Request 이벤트가 발생한 경우에 Workflow가 실행됩니다.
  # 만약 브랜치 구분 없이 이벤트를 지정하고 싶을 경우에는 단순히 아래와 같이 작성도 가능합니다.
  # on: [push, pull_request]
  push:
    branches: [dev]

# 해당 Workflow의 하나 이상의 Job 목록입니다.
jobs:
  # Job 이름으로, build라는 이름으로 Job이 표시됩니다.
  build:
    # Runner가 실행되는 환경을 정의하는 부분입니다.
    runs-on: ubuntu-latest

    # build Job 내의 step 목록입니다.
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.email ${{secrets.GIT_CONFIG_EMAIL}}
      - run: git config --global user.name ${{secrets.GIT_CONFIG_USER_NAME}}
      - name: cache Dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install

      - name: build
        run: yarn build

      - name: deploy
        run: yarn deploy
